language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
before_install:
  - composer selfupdate
  - composer install

script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/php-cs-fixer fix -v --dry-run --level=psr2 src
  - vendor/bin/phpmd src text phpmd.xml
